// import './images/h1.jpg'
export const data = {
    products: [
      {
        _id: '1',
        name: 'The Big house',
        category: 'House',
        image: `/images/house1.jpg`,
        price: 120000,
        address: {
            streetName: '93 Guild Rd',
            postcode: 'SE7 8HW',
            city: 'London',
            lat: 51.4741588,
            lng: 0.1823364
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 10,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '2',
        name: 'The Big house',
        category: 'House',
        image: `/images/house2.jpg`,
        price: 220000,
        address: {
            streetName: '46 Crown Street',
            postcode: 'SW9 3UJ',
            city: 'London',
            lat: 51.5715189,
            lng: -0.3418482
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 20,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '3',
        name: 'The Big house',
        category: 'House',
        image: `/images/house3.jpg`,
        price: 380000,
        address: {
            streetName: '15 Sandyhill Rd',
            postcode: 'CW7 1JP',
            city: 'Winsford',
            lat: 53.1807308,
            lng: 0.1823364
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 10,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '4',
        name: 'The Big house',
        category: 'House',
        image: `/images/house4.jpg`,
        price: 1150000,
        address: {
            streetName: '17 Wenlock Terrace',
            postcode: 'YO10 4DX',
            city: 'PENUWCH',
            lat: 53.9466238,
            lng: -1.075075
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 29,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '5',
        name: 'The Big house',
        category: 'House',
        image: `/images/house5.jpg`,
        price: 450000,
        address: {
            streetName: '37 Scarcroft Road',
            postcode: 'M12 4TH',
            city: 'PORTNACON',
            lat: 53.4625118,
            lng: -2.1925446
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 6,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '6',
        name: 'The Big house',
        category: 'House',
        image: `/images/house6.jpg`,
        price: 380000,
        address: {
            streetName: '43 Carriers Road',
            postcode: 'TN17 3EX',
            city: 'CREEDY PARK',
            lat: 51.0982119,
            lng: 0.5349951
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 80,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '7',
        name: 'The Big house',
        category: 'House',
        image: `/images/house7.jpg`,
        price: 420000,
        address: {
            streetName: '86 Asfordby Rd',
            postcode: 'LE14 3DT',
            city: 'ALDEBURGH',
            lat: 52.755272,
            lng: -0.9961887
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 14,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '8',
        name: 'The Big house',
        category: 'House',
        image: `/images/house8.jpg`,
        price: 260000,
        address: {
            streetName: '11 Broad Street',
            postcode: 'PE11 1TB',
            city: 'LOWER WOODEND',
            lat: 52.7881357,
            lng: -0.1500656
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 90,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '9',
        name: 'The Big house',
        category: 'House',
        image: `/images/house9.jpg`,
        price: 390000,
        address: {
            streetName: '49 Wartnaby Road',
            postcode: 'LE14 3JB',
            city: 'ADDIEWELL',
            lat: 52.8001966,
            lng: -0.9270139
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 19,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '10',
        name: 'The Big house',
        category: 'House',
        image: `/images/house10.jpg`,
        price: 250000,
        address: {
            streetName: '29 Sea Road',
            postcode: 'CT14 8BZ',
            city: 'LAMANCHA',
            lat: 51.1873569,
            lng: 1.3975221
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 50,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '11',
        name: 'The Big house',
        category: 'House',
        image: `/images/house11.jpg`,
        price: 310000,
        address: {
            streetName: '37 Trinity Crescent',
            postcode: 'PE21 9NX',
            city: 'Boston',
            lat: 52.9833175,
            lng: -0.0142408
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 33,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '12',
        name: 'The Big house',
        category: 'House',
        image: `/images/house12.jpg`,
        price: 495000,
        address: {
            streetName: '50 Nenthead Road',
            postcode: 'CA9 3TR',
            city: 'HIGHAM',
            lat: 54.8105589,
            lng: -2.4229553
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 15,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '13',
        name: 'The Big house',
        category: 'House',
        image: `/images/house13.jpg`,
        price: 395000,
        address: {
            streetName: '89 Roman Rd',
            postcode: 'TA1 2BH',
            city: 'Somerset',
            lat: 51.0200802,
            lng: -3.0784192
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 30,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '14',
        name: 'The Big house',
        category: 'House',
        image: `/images/house14.jpg`,
        price: 110000,
        address: {
            streetName: '17 Asfordby Rd',
            postcode: 'LE14 3DT',
            city: 'AIRD THUNGA',
            lat: 52.755272,
            lng: -0.9961887
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 45,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '15',
        name: 'The Big house',
        category: 'House',
        image: `/images/house15.jpg`,
        price: 250000,
        address: {
            streetName: '2 Hounslow Rd',
            postcode: 'TW2 7EX',
            city: "London",
            lat: 51.4534158,
            lng: -0.3577833
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 32,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '16',
        name: 'The Big house',
        category: 'House',
        image: `/images/house16.jpg`,
        price: 342000,
        address: {
            streetName: '24 Hertingfordbury Rd',
            postcode: 'SG14 2LJ',
            city: 'Hertingfordbury',
            lat: 51.7911362,
            lng: -0.1146488
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 58,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '17',
        name: 'The Big house',
        category: 'House',
        image: `/images/house17.jpg`,
        price: 160000,
        address: {
            streetName: '74 Shore Street',
            postcode: 'IV54 8LR',
            city: 'Applecross',
            lat: 57.4297682,
            lng: -5.8176362
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 21,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '18',
        name: 'The Big house',
        category: 'House',
        image: `/images/house18.jpg`,
        price: 340000,
        address: {
            streetName: '80 Whitby Road',
            postcode: 'CH65 9ER',
            city: 'Ellesmere Port',
            lat: 53.2766599,
            lng: -2.9057444
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 44,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '19',
        name: 'The Big house',
        category: 'House',
        image: `/images/house19.jpg`,
        price: 320000,
        address: {
            streetName: '46 Duckpit Lane',
            postcode: 'CT4 5QA',
            city: 'Petham',
            lat: 51.2059183,
            lng: 1.0371453
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 25,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '20',
        name: 'The Big house',
        category: 'House',
        image: `/images/house20.jpg`,
        price: 440000,
        address: {
            streetName: '80 Brackley Road',
            postcode: 'NN13 5PP',
            city: 'London',
            lat: 52.0079026,
            lng: -1.1957501
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 97,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '21',
        name: 'The Big house',
        category: 'House',
        image: `/images/house21.jpg`,
        price: 240000,
        address: {
            streetName: '49 Bury Rd',
            postcode: 'IP24 3DD',
            city: 'Breckland',
            lat: 52.4106453,
            lng: 0.7457544
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 30,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '22',
        name: 'The Big house',
        category: 'House',
        image: `/images/house22.jpg`,
        price: 320000,
        address: {
            streetName: '3 Constitution St',
            postcode: 'EH6 6RP',
            city: 'Edinburgh',
            lat: 55.9744773,
            lng: -3.1673101
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 16,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '23',
        name: 'The Big house',
        category: 'House',
        image: `/images/house23.jpg`,
        price: 200000,
        address: {
            streetName: '48 Rhosddu Rd',
            postcode: 'LL11 2NG',
            city: 'Wrexham',
            lat: 53.0531418,
            lng: -2.9968873
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 32,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '24',
        name: 'The Big house',
        category: 'House',
        image: `/images/house24.jpg`,
        price: 430000,
        address: {
            streetName: '86 Stroud Rd',
            postcode: 'GL4 0UJ',
            city: 'Brookthorpe',
            lat: 51.8089805,
            lng: -2.2397457
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 60,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '25',
        name: 'The Big house',
        category: 'House',
        image: `/images/house25.jpg`,
        price: 260000,
        address: {
            streetName: '51 Golf Road',
            postcode: 'CR8 5ES',
            city: 'London',
            lat: 51.3089071,
            lng: -0.0980928
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 50,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '26',
        name: 'The Big house',
        category: 'House',
        image: `/images/house26.jpg`,
        price: 320000,
        address: {
            streetName: '38 Eastbourne Rd',
            postcode: 'RH19 2RD',
            city: 'Felbridge',
            lat: 51.1471999,
            lng: -0.0422468
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 30,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '27',
        name: 'The Big house',
        category: 'House',
        image: `/images/house27.jpg`,
        price: 470000,
        address: {
            streetName: '63 Witney Way',
            postcode: 'NE35 9PF',
            city: 'London',
            lat: 54.9441905,
            lng: -1.4694943
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 50,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '28',
        name: 'The Big house',
        category: 'House',
        image: `/images/house28.jpg`,
        price: 129000,
        address: {
            streetName: '26 Glenurquhart Road',
            postcode: 'IV3 8JL',
            city: 'Inverness',
            lat: 57.4649704,
            lng: -4.2428121
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 20,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '29',
        name: 'The Big house',
        category: 'House',
        image: `/images/house29.jpg`,
        price: 420000,
        address: {
            streetName: '49 Hull Road',
            postcode: 'HU12 8ED',
            city: 'Hull',
            lat: 53.7444594,
            lng: -0.2450963
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 32,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '30',
        name: 'The Big house',
        category: 'House',
        image: `/images/house30.jpg`,
        price: 180000,
        address: {
            streetName: '51 Abingdon Road',
            postcode: 'W8 6AN',
            city: 'London',
            lat: 51.4982038,
            lng: -0.1961738
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 38,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '31',
        name: 'The Big house',
        category: 'House',
        image: `/images/house31.jpg`,
        price: 340000,
        address: {
            streetName: '45 Scarcroft Road',
            postcode: 'SW1X 9EH',
            city: 'London',
            lat: 51.4973779,
            lng: -0.15669
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 32,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
      {
        _id: '32',
        name: 'The Big house',
        category: 'House',
        image: `/images/house32.jpg`,
        price: 120000,
        address: {
            streetName: '77 Wenlock Terrace',
            postcode: 'YO10 4DX',
            city: 'York',
            lat: 53.9466238,
            lng: -1.075075
        },
        // countInStock: 10,
        // brand: 'Nike',
        // rating: 4.5,
        numVisits: 23,
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet non curabitur gravida arcu ac tortor dignissim. Convallis posuere morbi leo urna molestie. Sed viverra ipsum nunc aliquet bibendum. Elementum integer enim neque volutpat ac. Faucibus pulvinar elementum integer enim neque volutpat. Tellus cras adipiscing enim eu. Odio euismod lacinia at quis risus sed. Proin nibh nisl condimentum id venenatis a.',
      },
    ],
}
